### PR TITLE
Preform reservation

### PR DESCRIPTION
**Pull request by Marcraphael12**
In this PR, we are working on the reservation pages
- Create reducer actions
    - Add a reservation
    - delete a reservation
- Add reducer to the  store
- Add routes

[Back-end PR ](https://github.com/JavierAybar/Full_Stack_Capstone_Back_End/pull/26)

### CODE REVIEW

**Comment by JavierAybar** [comment]
Hello @Marcraphael12 

Please fix the linters problems.

in line 24 `package.json` change this:
```sh
"tailwindcss": "^3.3.3"
```
for this
```sh
"tailwindcss": "^3.3.3",
```
You just need to add a (,) this will solve your problem.

**Comment by JavierAybar** [comment]
Hello @Marcraphael12 
As you can see here, I'm getting errors when I try to verify your changes.

Captura de pantalla 2023-12-04 171729


- That seems to be related to the slice you are currently using it in in `MyReservation`, `NewCarReservation` and `NewReservation`.
- I think you are using the wrong slice (`import { fetchVehicleDetails } from '../../redux/vehicle_details/vehicleDetailsSlice';`) instead you should use `VehicleSlice`. 
- also in order to use `VehicleDetailsSlice` you should pass the `id` as arguments.
- I'm not sure if a `MyCarResertion` page is necessary. What I understood was that you have to create a page to show a user's reservation and another to create the reservation.

**Comment by Marcraphael12** [comment]
Thanks for your thought @JavierAybar, i had to use Vehicle Slice instead of vehicleDetailsSlice. I was a bit confused about that. Thanks!

**Comment by JavierAybar** [comment]
## Hello @Marcraphael12 
###  **Please test your changes before request a new review**

- kindly don't import thing that you don't have in your application such as :
`import '../../assets/style/NewReservation.css';`

**Comment by Marcraphael12** [comment]
Nope... I'm getting this error and pain to fix it... let me push the version I use
I want you to check it on your side and tell me what you think it is
image

**Comment by JavierAybar** [comment]
### Hello @Marcraphael12 

### Please do not change the code created by your teammates, you are breaking your partners' code. 🔴 

- Please, could you explain me, why you delete all the routes in `App.js` ?
- Please update your branch with the new changes. (`git merge origin dev`)
- You get an error related to .map because you are trying to access the data incorrectly, and you cannot create a reservation without a user_id, that is because you need to update your branch with the new changes, in order to create a user. and log in.

- Please review the changes requested yesterday 🟢 
As I told you this is the correct way to access the data

Please change this line should be:
```sh
 const vehicles = useSelector((state) => state.vehicle.vehicle);
```

### Remember to update your branch first to make more changes later.

**Comment by Marcraphael12** [comment]
Nope i'm not deleting my partner's code, just comment it as it's not necessary for testing mine.  i will make sure to take the new merged changes on the dev branch.

**Review by Abdelaziz-Mahdi — APPROVED** [review]
Well done approved 💯

**Pull request merged**
